version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user

hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 200
      runas: ec2-user
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 20
      runas: ec2-user